export { createDocument } from "./core/document.js";
export { applyPatch, materialize, validatePatch } from "./core/apply.js";
export { diffTrees, rebasePatch } from "./core/diff.js";
export { createEditor, patchBuilder } from "./editor/builder.js";
export {
  AmbiguousPositionError,
  DuplicateIdError,
  EditorNodeMissingError,
  EditorNodeTypeMismatchError,
  InvalidPointerError,
  InvalidRootError,
  InvalidSchemaError,
  MalformedPatchError,
  MalformedTreeError,
  MissingCodecError,
  MissingPatchIdError,
  TreePatchError,
  UnsupportedPatchOperationError,
  UnsupportedTransformError,
  UnsupportedRuntimeValueError,
} from "./core/errors.js";
export { defaultJsonValueAdapter, decodePersistedValue, encodePersistedValue } from "./schema/adapters.js";
export { pathToPointer, pointerToPath } from "./schema/pointers.js";

export type {
  AnyMaterializedNode,
  AnyTreeNode,
  ApplyOptions,
  ApplyResult,
  AttrPath,
  ChildPosition,
  CreateDocumentOptions,
  DeepPath,
  DeepValue,
  DiffOptions,
  EncodedValue,
  Guard,
  HideNodeOp,
  IndexedNode,
  IndexedTree,
  InsertNodeOp,
  JsonPointer,
  JsonValue,
  MaterializeOptions,
  MaterializeResult,
  MaterializedNode,
  MaterializedNodeState,
  MoveNodeOp,
  NodeId,
  NodeRuntimeSpec,
  NodeTypeMap,
  PatchConflict,
  PatchOp,
  PersistedValue,
  RebaseOptions,
  RebaseResult,
  RemoveAttrOp,
  RemoveNodeOp,
  ReplaceSubtreeOp,
  RevisionStatus,
  SerializedPatchNode,
  SetAttrOp,
  ShowNodeOp,
  TreeCache,
  TreeDocument,
  TreeIndex,
  TreeNode,
  TreePatch,
  TreeSchema,
  ValidateOptions,
  ValidationResult,
  ValueAdapter,
  ValueCodec,
} from "./core/types.js";
export type {
  CreateEditorOptions,
  NodeEditor,
  PatchBuilder,
  PatchBuilderFieldOptions,
  PatchBuilderOptions,
  TreeEditor,
} from "./editor/builder.js";
